### ISSUE TITLE
Get user timezones from Slack API

### ISSUE THREAD

**Issue by mtthwhggns** [mtthwhggns/tomatobot#21]
Store the user's timezone (or maybe offset) in the database, use it to ensure that a review of today is since midnight in their timezone.

**Comment by lshearer** [comment]
Does this even need stored? Can it be efficiently accessed when a review is requested? For users traveling between timezones it would be handy to not need updating this in the db.

**Comment by mtthwhggns** [comment]
I'm not interested in making users update this themselves (as is the option at the moment), but in automatically grabbing it from the Slack API. 

I'm inclined towards storing it rather than waiting on the Slack API for every request, as I'm quite happy with the response times at the moment, but there would be no problem with refreshing it at the time of, say the first request each 24h.

At the moment, there are some limitations, as I'm reluctant to require access to the directory of user profiles, but that's the API's only way to see individual timezones. I've raised this with Slack, but so far, nothing helpful has come out of it.
