### ISSUE TITLE
Needs to indicate which user's review

### ISSUE THREAD

**Issue by emilymerwin** [mtthwhggns/tomatobot#31]
There's no indication of who's review it is (the slash command shows up userless?), so the `/review public` option is awkward.
![screen shot 2016-04-21 at 12 07 47 am](https://cloud.githubusercontent.com/assets/2807848/14697789/4d53b2ea-0755-11e6-9934-37257717082f.png)

**Comment by mtthwhggns** [comment]
As `/review public` Is visible to the whole channel, the message that requested it will always be visible to the channel too. 

In my tests, the slash command doesn't show as user-less, so I can't understand why it is doing now. 

I will investigate this a little bit more, but if adding a username at the top of the review will solve it, that can be done easily.

**Comment by emilymerwin** [comment]
For some reason, when I created this issue `/review public` did not post with my user id or avatar (as you can see from the screenshot). But I just tried it and my user info did show as it should... so maybe it was a fluke? Sorry, guess you can close this.

**Comment by mtthwhggns** [comment]
Yeah, I'll close this for now, not sure what happened.

If it happens again, let me know, I'd be curious to try and figure out why this happens!
