### ISSUE TITLE
Move commands under a general /tomatobot command

### ISSUE THREAD

**Issue by mtthwhggns** [mtthwhggns/tomatobot#47]
As per Slack's suggestion, it would be easier, particularly with timing breaks, if we could keep all tasks under a single command, so I'll look into having a single command, and a service to handle each.

It will probably be very similar to the current setup;

> /tomatobot start

This opens up the possibilities to things like

> Time for a 5 minute break. Would you like me to let you know when five minutes are up?
> 
> /tomatobot yes

Which will allow us to deal with #36

**Comment by lshearer** [comment]
I think this will make it easier to remember what commands are available to use, as well as prevent collision or confusion with other integrations.
