### ISSUE TITLE
Add ability to cancel running pomodoro

### ISSUE THREAD

**Issue by lshearer** [mtthwhggns/tomatobot#48]
I'm not very experienced with the pomodoro method, so I don't know if this goes against some sort of principle. But, it would be nice to be able to cancel the currently running pomodoro. 

This was especially noticeable when testing out the slack integration and wanting to end the test pomodoro. I could also see use during normal work, though: if you accidentally start a pomodoro (maybe using the wrong command) or start a pomodoro and then realize you won't be able to properly finish it (upcoming meeting, etc.).

**Comment by mtthwhggns** [comment]
I'll think about this, but I've got a bunch of things which will have to come first. 

I originally wanted the app to mimic a real physical timer, so not being able to stop it was part of the design, but this is a question that comes up from time to time, so, once I get the rest of the backlog done, I might look at it again.

**Comment by lshearer** [comment]
Yep, that's fair.

As far as modeling a physical timer, another option might be allowing restarting the timer instead of simply canceling it. This would be comparable to cranking the timer back up to 25 min.

**Comment by dogeared** [comment]
Thanks for the work on this! I've been using this with a team of 4 on Slack and it's really helped us. Interrupting or canceling a pomodoro is a part of the process. Here's a link to the wiki page with the relevant section highlighted: http://scrible.com/s/ifwk6

I am thinking a `/stopwork`, `/abandon` or `/interrupt` would be good.

Thanks again!
