### ISSUE TITLE
Add option to update user "status" during active pomodoro

### ISSUE THREAD

**Issue by lshearer** [mtthwhggns/tomatobot#49]
I've been loving using tomatobot, especially the Do Not Disturb feature to minimize interruptions. 

However, I _have_ had a couple coworkers ask about the odd Do Not Disturb hours. It would be nice to let coworkers know why I don't want to be disturbed at the moment, especially those coworkers I don't work with on a daily basis. Essentially, some way of helping convey "I don't want to be disturbed _right now_, but I'll be available soon, so go ahead and ask me questions".

I'm not sure if this is common, but at my company many people add a status when they're doing something noteworthy (especially if they're in Do Not Disturb during normal working hours). They do this by suffixing the Last Name field in their profile with the status. Then, others can easily see that status in channels and direct messages. E.g., `Lyle Shearer | heads down (v3.3 release)`, where `Shearer | ...` is stored in the last name profile field.

I started manually editing my name when I'm starting pomodoro activities for the day, then removing the status if I'm done for the day or doing non-pomdoro style work. This can be hard to remember though and would be nice if it happened automatically as part of an active pomodoro. This would also be more accurate and could allow for more precise statuses, because it would only show when I am currently in an active pomodoro.

At its simplest, I could see this as an optional string suffix field that you can set in the tomatobot options, like `| in a 🍅`. Then, when a pomodoro starts, Do Not Disturb is enabled and the suffix is appended to the last name field (if it's not already there). Then when the pomodoro ends, Do Not disturb is disabled again and the suffix is removed (if still present). I'm sure there are a lot of edge case issues here, but nothing that manually editing the last name couldn't fix if things got weird.

Anyway, I just want to get your thoughts on the idea and if you think it's worth implementing in some form. I know it's possible (a coworker wrote a tool to do something similar with active calendar events), but I don't know the level of effort or permissions required. I'd love to help, too, though I am new to Slack app development and have not worked with rails either.

**Comment by ppeble** [comment]
I think this is a good idea, we do it too! I'm interested in adding it but I'm not sure when/if I will have time. I will try to do it in the coming week(s).

**Comment by lshearer** [comment]
This should be nicer to do now with an API for setting Slack statuses.

**Comment by mtthwhggns** [comment]
Yep, there's a very nice API for statuses, which I'll take a look at soon.
