### ISSUE TITLE
Allow for configurable pomodoro lengths

### ISSUE THREAD

**Issue by theTrueMikeBrown** [mtthwhggns/tomatobot#53]
My team uses 50 minute pomodoros with 10 minute breaks in between. Would it be possible to add to the startwork command a optional parameter to say how long your pomodoro will be?

I don't do much ruby or I'd make a pull request myself.

**Comment by mtthwhggns** [comment]
Technically, that is pretty straightforward to build.

The original idea was to keep as close as possible to the published "Pomodoro technique", which specifies 25 minutes. I believe this because it's a typical amount of time that people can focus without getting distracted.

However, this is a question that comes up somewhat regularly, so I guess I may get around to doing it, although, it won't be until I've dealt with the other things that are outstanding.

**Comment by theTrueMikeBrown** [comment]
I have a coworker who codes more ruby, and we looked at it.

It feels like if startwork were changed to the following:

 def startwork
    return help_response if help_requested?
    return already_active_response if task_active?
    task = Task.create(user: @user, team: @team)
    ActivateDndWorker.perform_async(@user.id) if start_dnd?
    **durationParam = params[:duration]
    duration = durationParam != nil ? durationParam : unit_duration.minutes**
    EndTaskWorker.perform_in(**duration**,
                             task.id, 
                             params[:response_url],
                             start_dnd?)
    render json: response_json(started_work_message, response_type)
  end

It might be sufficient, however we haven't tested this at all. How do you test these things on your box? do you have a instance of slack that you can run it against?

We could submit a pull request if you want (my coworker wants to make a test app, but I am willing to test this out in whatever way you usually do).

Thanks!

**Comment by mtthwhggns** [comment]
The Slack API is quite particular about how it accepts and provides different arguments, so `params[:duration]` won't work with Slack. 

The alternative, if you want this quicker than I can do it, is you fork the repo, change the value in the code and deploy a new copy onto your own server. It's all quite open and free to play around with.

**Comment by rosaaava** [comment]
Happily figured out that task duration was customizable but came across an issue: it appears as though the "time's up" notification only appears for 25-minute tasks. Also, under custom times, it looks like distractions aren't recorded at all. Is this a known issue?

Thanks for the work on Tomatobot!
