### ISSUE TITLE
Notifications On Slack Mobile app

### ISSUE THREAD

**Issue by vahit** [mtthwhggns/tomatobot#58]
Hi guys
I use as tomatobot on slack mobile application, but when i start a pomodoro period, tomatobot dont send "period completion" notification to me!
What should i do for resolve this problem?

**Comment by mtthwhggns** [comment]
Tomatobot doesn't control Slack notifications, you need to configure those yourself. in Slack yourself. You'll either get notifications or not depending on the channel you use to `/startwork`. Check the settings for the channel you use. 

Unfortunately, there's not really anything we can do on the Tomatobot side.

**Comment by vahit** [comment]
Hi again
I shared this issue with slack support team and I received this answer:

> Hi Vahit,
> Thanks for getting back to me, and for the screenshot! I'm afraid that it looks like Tomatobot is sending ephemeral messages to these channels, instead of regular messages, which is why you haven't been receiving mobile notifications from this app. Sorry about that!
> Ephemeral messages are different than our regular messages in that they aren't sent to our servers and only exist on the device that generated them. This is also why these messages don't have a message link associated with them.
> 
> Our desktop apps, as well as browser based Slack's are able to generate their own notifications, which is why these messages are able to generate a notification when posted to a channel with notifications for "All Activity" enabled.
> 
> However, our mobile apps aren't able to generate their own notifications locally in this way, and rely on having these messages relayed to them via our backend servers. Because these messages aren't being sent to our servers, they aren't able to be relayed back to the mobile app as notifications.
> 
> I'm afraid that it looks like the developer will have adjust Tomatobot to send regular Slack messages instead of ephemeral ones so we can relay the notifications properly.
> 
> I'm very sorry for this trouble, and that I don't have better news for you. If there's anything else I can do to help though, please let me know.

Now, can you help me to resolve this problem?

**Comment by mtthwhggns** [comment]
You can send messages to the current channel instead of using ephemeral messages by using `/startwork public`, however be aware that these will be visible to all team members.

Since most people don't want to share the notifications with the whole team, ephemeral messages can stay as the default.

**Comment by vahit** [comment]
Still pomodoro completion message 

> Time is up! Don't forget to tell me what you got done in the last 25 minutes, by typing `/completed` followed by a few words about what you got done. You didn't tell me about any distractions, well done! Take a quick five minute break, then we can get back to work.


 dont appear in my slack app (android device)!!
