### ISSUE TITLE
bot "failed with the error "curl_error_56""

### ISSUE THREAD

**Issue by sarahcn** [mtthwhggns/tomatobot#61]
The past several days I've been unable to use the Slack plug in. I get the error "failed with the error "curl_error_56"" whenever I try the /startwork command. Also looks like the webpage is unreachable. https://tomatobot.matthewhiggins.me/. 
Is this app still functional? Thanks!

**Comment by mtthwhggns** [comment]
Yes, the cluster this was hosted on crashed and I haven't had time to rebuild it yet.

In the meantime, it's unpublished from the Slack app directory, and I'll try and get a static page there to note what's happened ASAP.

You're welcome to grab the code and set up your own copy, but I can't give an estimate of when I'll get this fixed at the moment.
